server:
  port: 9527
spring:
  application:
    name: springcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh    # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://springcloud-provider-dept
          predicates:  #官网有很多断言规则，有cookie等判断，加强断言判断
            - Path=/dept/get/**   #断言,路径相匹配的进行路由
            - After=2021-07-22T11:46:47.372+08:00[Asia/Shanghai]

eureka:
  instance:
    hostname: springcloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://zty1.com:7001/eureka/


