server:
  port: 8401

#spring配置
spring:
  application:
    name: sentinel-provider-dept
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel  dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，假如会被占用会自动从8719开始依次加一扫描，直至找到未被占用的端口
        port: 8719
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
#mybatis配置
mybatis:
  type-aliases-package: com.zty.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml